spring:
  application:
  name: task-tracker-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  cors:
    allowedOrigins: http://localhost:4200

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY:word}