create table users(
    id int primary key generated by default as identity,
    firstName varchar(255) not null,
    lastName varchar(255) not null,
    login varchar(255) unique,
    password varchar(255) not null
);

create table tasks(
    id varchar(255) primary key,
    title varchar(255) not null,
    description varchar(255),
    is_completed boolean,
    created_at timestamp,
    finished_at timestamp,
    user_id int references users(id)
)